#cloud-config
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

runcmd:
  # Instalar Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install -y docker-ce docker-ce-cli containerd.io
  - sudo systemctl start docker
  - sudo systemctl enable docker
  - sudo usermod -aG docker adminuser

  # Instalar Docker Compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

  # Descargar el compose de producción y levantar los servicios
  - mkdir -p /home/adminuser/app
  - curl -L "https://gist.githubusercontent.com/Tiago0507/5f631df9281b10e2ba634512590036f1/raw/3ee1240a70111db0920ccf883a8cafaf20b5f205/docker-compose.prod.yml" -o /home/adminuser/app/docker-compose.prod.yml
  - cd /home/adminuser/app
  - sudo docker-compose -f docker-compose.prod.yml up -d