name: CI - Docker Compose Health Checks

on:
  push:
    branches: [ main, feat/dev/pipelines ]
  pull_request:
    branches: [ main ]

jobs:
  compose-health:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Ensure script is executable
        run: chmod +x scripts/health-check.sh

      - name: Run Docker Compose health checks
        run: |
          ./scripts/health-check.sh

      - name: Upload compose logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compose-logs
          path: compose-logs.txt


