name: Auth API - Build, Push & Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'microservices/auth-api/**'
      - '.github/workflows/cicd-auth-api.yml'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service_name: auth-api
    secrets: inherit