name: Users API - Build, Push & Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'microservices/users-api/**'
      - '.github/workflows/cicd-users-api.yml'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service_name: users-api
    secrets: inherit