name: Todos API - Build, Push & Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'microservices/todos-api/**'
      - '.github/workflows/cicd-todos-api.yml'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service_name: todos-api
    secrets: inherit