name: Frontend - Build, Push & Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'microservices/frontend/**'
      - '.github/workflows/cicd-frontend.yml'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service_name: frontend
    secrets: inherit