name: Log Message Processor - Build, Push & Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'microservices/log-message-processor/**'
      - '.github/workflows/cicd-log-processor.yml'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service_name: log-message-processor
    secrets: inherit