name: Infracost - Estimación de Costos en PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'iac/**'

jobs:
  infracost:
    name: Estimar costos con Infracost
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Configurar Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: 3. Generar el reporte de diferencia de costos
        run: |
          infracost diff --path ./iac \
            --format=json \
            --out-file=/tmp/infracost.json \
            --terraform-var="admin_password=${{ secrets.SSH_PASSWORD }}"

      - name: 4. Publicar comentario en el Pull Request
        run: |
          infracost comment github --path "/tmp/infracost.json" --behavior update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}